# Generated by Django 4.1.6 on 2024-04-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker', '0002_boost'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='lvl',
            field=models.IntegerField(default=0),
        ),
    ]
